name: Integration Test

on:
  push:
    branches: [ devs]
    paths:
      - 'web-app/**'
  pull_request:
    branches: [main]
    paths:
      - 'web-app/**'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    if: false
    defaults:
      run:
        working-directory: ./web-app
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./web-app/package-lock.json
      - run: npm ci
      - run: npm test

  build:
    runs-on: ubuntu-latest
    if: false
    defaults:
      run:
        working-directory: ./web-app
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./web-app/package-lock.json
      - run: npm ci
      - run: npm run build

  coverage:
    runs-on: ubuntu-latest
    if: false
    defaults:
      run:
        working-directory: ./web-app
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./web-app/package-lock.json
      - run: npm ci
      - run: npm test -- --coverage
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: web-app/coverage