name: Playwright Tests

on:
  push:
    branches: [main, master]
    paths:
      - 'web-app/**'
  pull_request:
    branches: [main, master]
    paths:
      - 'web-app/**'

jobs:
  test_e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: false
    defaults:
      run:
        working-directory: ./web-app
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: web-app/playwright-report/
        retention-days: 30